package com.ef.cim.objectmodel;

public enum MessageIntent {
    NONE,
    REPLY_TO,
    UPDATE,
    START_CHAT,
    END_CHAT,
    CALL_LEG_STARTED,
    CALL_LEG_ENDED,
    AGENT_OUTBOUND,
    START_VOICE,
    END_VOICE,
    NETWORK_DISCONNECT,
    ASSIGN_RESOURCE_REQUESTED,
    CANCEL_RESOURCE_REQUESTED,
    IVR_AGGREGATED_ACTIVITY,
    START_CONVERSATION,
    CALL_HOLD,
    CALL_RESUME,
    VOICE_CALL_RECORDING,
    WRAPUP,
    MEDIA_RECORDING,
    QM_ACTIVITY,
    CALL_ALERTING,
    VOICE_MAIL_ACTIVITY
}