package com.ef.cim.objectmodel;

public enum NotificationType {
    INFO,
    SYSTEM_ERROR,
    WARNING,
    CHANNEL_SESSION_STARTED,
    CHANNEL_SESSION_EXPIRED,
    CHANNEL_SESSION_ENDED,
    AGENT_SUBSCRIBED,
    AGENT_UNSUBSCRIBED,
    CONSULT_TRANSFERRED,
    CONSULT_CONFERENCED
}