package com.ef.cim.objectmodel;

public enum NotificationType {
    INFO,
    SYSTEM_ERROR,
    WARNING,
    CHANNEL_SESSION_STARTED,
    CHANNEL_SESSION_EXPIRED,
    CHANNEL_SESSION_ENDED,
    AGENT_SUBSCRIBED,
    AGENT_UNSUBSCRIBED,
    TASK_ENQUEUED,
    NO_AGENT_AVAILABLE,
    TYPING_STARTED,
    TYPING_STOPPED,
    AGENT_RESERVED,
    PARTICIPANT_ROLE_CHANGED,
    TASK_STATE_CHANGED,
    CHANNEL_SESSION_DATA_UPDATED
}